# Generated by Django 5.0.6 on 2025-06-25 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_name', models.CharField(max_length=50)),
                ('resource_file', models.FileField(upload_to='resources/')),
                ('resource_type', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='resources.resourcetype')),
            ],
        ),
    ]
