# Generated by Django 5.0.6 on 2024-06-03 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_tasklist_employee_alter_tasklist_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasklist',
            old_name='Employee',
            new_name='employee',
        ),
    ]
