# Generated by Django 5.0.6 on 2025-06-25 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True,
                                           serialize=False,
                                           verbose_name='ID')),
                ('department_name', models.CharField(max_length=50)),
                ('dep_description', models.TextField()),
                ('emp_num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Head',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('head_name', models.CharField(max_length=100)),
                ('department', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='departments.department')),
                ('position', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='accounts.position')),
            ],
        ),
    ]
